### ISSUE TITLE
LUA Error on MouseOver items in any TSM4 Frame.

### ISSUE THREAD

**Issue by fubaBfA** [arkayenro/arkinventory#1074]
Hi there,
another error that just triggers when MouseOver an Item in any TSM4 Frame that shows any Item Links.
Tested on TSM Auction Frame and TSM Group Frame.

I feel you must hate TSM4 more and more :D
```
1x ArkInventory\ArkInventoryTooltip.lua:1713: attempt to index a nil value
ArkInventory\ArkInventoryTooltip.lua:1713: in function `TooltipAddOnUpdate'
ArkInventory\ArkInventoryTooltip.lua:561: in function `GameTooltipHookSetGeneric'
ArkInventory\ArkInventoryTooltip.lua:606: in function <ArkInventory\ArkInventoryTooltip.lua:605>
(tail call): ?
[C]: ?
[C]: ?
[C]: in function `?'
ArkInventory\ArkInventoryTooltip.lua:1694: in function `UpdateTooltip'
FrameXML\GameTooltip.lua:500: in function <FrameXML\GameTooltip.lua:477>
[C]: ?
[C]: ?

Locals:
tooltip = GameTooltip {
 0 = <userdata>
 SetCurrencyByID = <function> defined =[C]:-1
 SetQuestLogRewardSpell = <function> defined =[C]:-1
 SetText = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 SetPvpTalent = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 template = "Transparent"
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 numMoneyFrames = 2
 SetCurrencyToken = <function> defined =[C]:-1
 SetQuestRewardSpell = <function> defined =[C]:-1
 hasMoney = 1
 Hide = <function> defined =[C]:-1
 ClearLines = <function> defined =[C]:-1
 comparing = false
 ARKTTD = <table> {
 }
 TopOverlay = <unnamed> {
 }
 SetArtifactPowerByID = <function> defined =[C]:-1
 ARK_Data = <table> {
 }
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetLFGDungeonReward = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetToyByItemID = <function> defined =[C]:-1
 SetQuestLogSpecialItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined =[C]:-1
 SetQuestCurrency = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetCurrencyTokenByID = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 SetBackpackToken = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 SetSpellByID = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 SetTradeTargetItem = <function> defined =[C]:-1
 SetSendMailItem = <function> defined =[C]:-1
 SetRecipeRankInfo = <function> defined =[C]:-1
 updateTooltip = 0.2
 SetInventoryItem = <function> defined =[C]:-1
 SetTalent = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetUnitAura = <function> defined =[C]:-1
 ignoreUpdates = true
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetAction = <function> defined =[C]:-1
 SetRecipeResultItem = <function> defined =[C]:-1
 SetQuestLogCurrency = <function> defined =[C]:-1
 SetAuctionItem = <function> defined =[C]:-1
}
fn = "SetHyperlink"
pre = nil
post = nil
(*temporary) = nil
(*temporary) = GameTooltip {
 0 = <userdata>
 SetCurrencyByID = <function> defined =[C]:-1
 SetQuestLogRewardSpell = <function> defined =[C]:-1
 SetText = <function> defined =[C]:-1
 SetLootItem = <function> defined =[C]:-1
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 SetPvpTalent = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined =[C]:-1
 template = "Transparent"
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 numMoneyFrames = 2
 SetCurrencyToken = <function> defined =[C]:-1
 SetQuestRewardSpell = <function> defined =[C]:-1
 hasMoney = 1
 Hide = <function> defined =[C]:-1
 ClearLines = <function> defined =[C]:-1
 comparing = false
 ARKTTD = <table> {
 }
 TopOverlay = <unnamed> {
 }
 SetArtifactPowerByID = <function> defined =[C]:-1
 ARK_Data = <table> {
 }
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetLFGDungeonReward = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetToyByItemID = <function> defined =[C]:-1
 SetQuestLogSpecialItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined =[C]:-1
 SetQuestCurrency = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined 
```

**Comment by arkayenro** [comment]
i think thats been fixed in the 756 alpha

**Comment by fubaBfA** [comment]
Oh damn you're fast!
i just have updated to 755.
I'll test it, thanks :D

**Comment by fubaBfA** [comment]
Yep it is Fixed.
**Thank you again** :)

**Comment by fubaBfA** [comment]
Today i saw the Bug is not really fixed :/  
Interesting is there is no LUA Error anymore **but** the Tootlips still disappear in any TSM Frame after about 1-2 seconds.
This is very annoying if i need to read some texts from the eg. the AH Tooltip :(
