### ISSUE TITLE
Item Counts in Tooltips don't Update

### ISSUE THREAD

**Issue by Calesta** [arkayenro/arkinventory#722]
In the latest version, the tooltip counts aren't updating.  For example, before when I looted a new item the count would be increased when I hovered over the link.  Now, the number stays static and it doesn't update again unless I reload the UI.

**Comment by Calesta** [comment]
Actually, it just seems that the counts are delayed.  Different behavior than before but maybe it's by design?

**Comment by spiralofhope** [comment]
I'd bet it's by design, because frequent tooltip updating is so absolutely horrifying to the point of reducing frame rates.

**Comment by Yanngo** [comment]
The bug is more complicated.
Unfortunately, ArkInventory does not show whether my characters have a certain selection of items. Those items include but not limited to necks, trinkets, bracers that drop from Kazzak in Draenor.
And all kinds of gear produced by using baleful tokens.

**Comment by arkayenro** [comment]
there was a bug with how i checked new items, part of that check updated the item counts but i was checking blizzards new item flag first, so when that was true, it didnt do my check, or the item count update.

i've swapped the logic around so it does my check first and that appears to have fixed the issue.

fixed in 3.06.00

**Comment by Yanngo** [comment]
Seems the issue persists in some way. **ArkInventory version 3.06.14**

Just bought a bunch of death knight tier gear for gold from this guy
http://www.wowhead.com/npc=38316/ormus-the-penitent#sells:0+17-2

The items transferred from the vendor to my bags were not mentioned in the tooltip. Even after some time. The item counts appeared after I did `/reload`.

**Comment by arkayenro** [comment]
i'll see if i can figure out whats happening

**Comment by arkayenro** [comment]
this should be fixed in 30700 beta onwards, if its not let me know
