### ISSUE TITLE
All Options are locked

### ISSUE THREAD

**Issue by GreenNite** [arkayenro/arkinventory#765]
When I go to change a bar option, it says the bar is locked, the sort option is locked and the assigned category is locked. I have tried reinstalling it

**Comment by arkayenro** [comment]
go into the config and then to controls

setup the layout options in there for each location so they are not using "* Default"

**Comment by Zananos** [comment]
I've tried that myself and have had 0 success, then tried deleting everything and making new with no success, uninstalled and reinstalled with no success and made new names for a profile and new sets in settings and set those instead of default in the controls tap with no success...

**Comment by Zananos** [comment]
Ah finally... completely exited the game after that final one adjusting something else I don't recall and they work now

**Comment by GreenNite** [comment]
The only option I see in there id the Default and Guild Bank Default

**Comment by joelgriffiths** [comment]
We need to make a new layout but I can't find a place to do so.

**Comment by jbresciani** [comment]
to create a new layout go into Config -> Settings -> Design (tab) and add a new one, then go back into Config -> Controls -> Bag (tab) and change the layout, I also created a new category set (from settings) and set that in Controls Bag as well

After then reload UI and it starts working again

**Comment by GreenNite** [comment]
That got it!!

Thanks All

**Comment by GreenNite** [comment]
OOPS, spoke to soon, the Assignable Categories is still messed up so I can not change an items category

**Comment by GreenNite** [comment]
Am I the only one having this issue?

**Comment by arkayenro** [comment]
i found an issue where the settings may not always update, will be fixed in .10 and you shouldnt have to reload to get them to kick in

**Comment by Bigman1182** [comment]
I am having this problem as well. I cant edit any bags, all are saying locked.

**Comment by Yanngo** [comment]
If you have problems with sorting your bags, bank, void storage and so on:
1. Go to Config >> Controls.
2. On every tab under the Blueprint name change the dropdown menus Style, Category Set, and Layout to the names you'd been using before patch 7.0.
3. The dropdown menus Style, Category Set, and Layout  MUST NOT contain the word Default. If it does, assigning categories to items will not work.

**Comment by EJ9** [comment]
Ahh Perfect. The .10 update fixed my Profilesettings :-) 
Thanks for the good work

**Comment by arkayenro** [comment]
.11 should fix the categories

**Comment by GreenNite** [comment]
ok, that fixed it so I can edit the items and everything else. Where do I change the size though?

**Comment by arkayenro** [comment]
size of?

should be under one of the style options

**Comment by dgrove21** [comment]
After the patch,  and 2 updates from Curse, reloading,  creating new category, and doing everything thus far suggested,  it still does not work. I am attaching a screenshot of what I see, and have yet to discover what to do about it.  It occurred to me that maybe there was some kind of conflict..  Any ideas would be appreciated.  

![image](https://cloud.githubusercontent.com/assets/20568983/17011027/7a2b6424-4ed7-11e6-9d6e-04362e361c41.png)
![image](https://cloud.githubusercontent.com/assets/20568983/17011035/91e72e4a-4ed7-11e6-9239-e5bcef2a3957.png)

**Comment by Yanngo** [comment]
Imagine your old profile name is ANEW and try this:
https://www.youtube.com/watch?v=f_XFlsAYBho

**Comment by GreenNite** [comment]
Unless I am having a blond moment, I cannot find anything that says style

**Comment by Yanngo** [comment]
Here http://imgur.com/x4j7xGj
And give me a screenshot like this
http://imgur.com/ocGYGEs

**Comment by arkayenro** [comment]
fixed in .15

editable default

**Comment by dgrove21** [comment]
The latest version seems to have fixed the problem.  So Far, it seems all is well.  Glad to have it back.  It is so superior to Bagnon, and OneBag.

**Comment by OneOfA11** [comment]
Is this some kind of joke? You are not updated your Wiki and you are going with your old bullshit "go into the config and then to controls", CONTROLS are not presented anymore in the latest version. This shit happened because of your note "remove profile" and now everything is FUCKED UP and bags are looking like shit, no item level, no borders, wasn't able to set filters, JUST PURE NOTHING!
